name: scamandrill
markdown: redcarpet
pygments: true
license: http://www.apache.org/licenses/LICENSE-2.0.html
url: http://dzsessona.github.io/scamandrill
    
github:
  author: dzsessona
  project: scamandrill
  
